### ISSUE TITLE
Shadow with opacity less then .3 is invisible.

### ISSUE THREAD

**Issue by vasilich6107** [johynpapin/flutter_inset_shadow#7]
<img width="724" alt="image" src="https://github.com/johynpapin/flutter_inset_box_shadow/assets/6721286/a817c1c4-8a14-4aa4-a630-0683457d7d8b">

Same params in chrome

<img width="922" alt="image" src="https://github.com/johynpapin/flutter_inset_box_shadow/assets/6721286/5090d9f7-453b-4999-b3d5-034283046bb2">

**Comment by vasilich6107** [comment]
Seems like this fixes the issue without causing differences in opacity: 1

Could you clarify if it is viable solution?

<img width="1675" alt="image" src="https://github.com/johynpapin/flutter_inset_box_shadow/assets/6721286/d45ca6b5-5309-4a9d-93b5-069ca5a116af">

**Comment by ghost** [comment]
You'll laugh: I unfortunately lost my access to https://pub.dev because I deleted my Google account. I'll contact the support to get my access back, and as soon as it's done I'll be able to deploy version 2, and thus close this issue.

Sorry for the extra delay. :pensive:

**Comment by vasilich6107** [comment]
No problem.
Good luck with support

**Comment by ghost** [comment]
Hello !

I never got a reply from support, so I've decided to publish the package under a new name!
You can find it here: https://pub.dev/packages/flutter_inset_shadow. :smile:

I removed the `box` from the name because of #5. :smile:

Thank you again @vasilich6107 and @ksokolovskyi for your contributions! Don't hesitate if you'd like to change anything in the package! :heart:
